### ISSUE TITLE
couldn't find required mod 

### ISSUE THREAD

**Issue by phinniez** [skyrising/skyblock#2] opened 2019-11-23 16:04 UTC
i've installed both of quickcarpet, skyblock these on my server but for some reason i get this error
https://github.com/DeadlyMC/QuickCarpet114/releases/tag/1.13.0 
https://github.com/skyrising/skyblock/releases/tag/v1.0-fc

root@minecraft:/home/minecraft# java -Xmx7168M -Xms4096M -jar fabric-server-launch.jar nogui
[15:53:29] [main/INFO]: Loading for game Minecraft 1.14.4
net.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: skyblock requires {carpet @ [*]}
        at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:170)
        at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:603)
        at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:176)
        at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:166)
        at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:127)
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:26)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:61)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:105)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:49)
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
        at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117)
        at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97)
        at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStru
ctureDanielWL.java:81)
        at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401)
        at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:168)
        ... 12 more

**Comment by skyrising** [comment] 2019-11-23 16:06
Duplicate of #1 (you're using the fabric-carpet version of skyblock with quickcarpet)

**Closed as completed by skyrising** 2019-11-23 16:06 UTC
Labels: duplicate

**Comment by phinniez** [comment] 2019-11-23 16:10
i didn't really solution what should i do can you explain it like you are explaining it to a newbie about this stuff
